dist: trusty
language: python
python:
- '3.6'

git:
  # needed for version tracking (setuptools-scm)
  depth: 99999

cache:
  directories:
    - $HOME/.cache/pip

# Install required packages
addons:
  apt:
    sources:
      - sourceline: ppa:nextgis/ppa
    packages:
      - gdal-bin
      - gdal-data
      - libgdal-dev
      - libgdal20
      - libudunits2-0

before_install:
  - pip install --upgrade pip
  - pip install wheel
  - pip install setuptools-scm

# aiobotocore is tricky because of the narrow dependencies on botocore
# best to install it early before botocore is pulled in by other libs
  - pip install -U 'aiobotocore[boto3]'

# GDAL install
  - export CPLUS_INCLUDE_PATH=/usr/include/gdal
  - export C_INCLUDE_PATH=/usr/include/gdal
  - export GDAL_DATA="$(gdal-config --datadir)"
  - gdal-config --version
  - pip install GDAL=="$(gdal-config --version)"
# datacube install
  - pip install -r "./scripts/travis-req.txt"
  - pip install datacube

install:
  - pip freeze

script:
  - ./scripts/travis.sh
  - pip freeze
  - find wheels

# On success, upload a package to an S3 Bucket. Used for continuous deployment.
deploy:
  # Deploy the sdist tarball and bdist_wheel to s3 for tags or the master branch
  # It can be installed via
  #   pip install --extra-index-url https://packages.dea.gadevs.ga/ odc-{ui,index..}
  - provider: s3
    bucket: "datacube-core-deployment"
    region: "ap-southeast-2"
    local_dir: wheels
    skip_cleanup: true
    on:
      all_branches: true  # Let the condition below decide if the branch is to be deployed
      condition: $TRAVIS_BRANCH = "master" || ! -z "${TRAVIS_TAG}"  # master branch or tags
      repo: opendatacube/odc-tools
      python: "3.6"
